### ISSUE TITLE
Review and fix doc for builder and post-Processor components

### ISSUE THREAD

**Issue by chomatdam** [pelotech/packer-plugin-kubevirt#13]
## Tasks

- [ ] Fix broken links (`builder` and `post-processor` links in [docs](https://github.com/pelotech/packer-plugin-kubevirt/tree/main/docs))
- [ ] Review required/optional builder fields in the docs
- [ ] Review required/optional post-processor fields in the docs
